
   @Author: v sanjay kumar<br>
   @Date: 2024-07-18 10:00:30<br>
   @Last Modified by: v sanjay kumar<br>
   @Last Modified time: 2024-07-18 10:00:30<br>
   @Title : Flip Coin and print percentage of Heads and Tails<br>

In [41]:
import boto3
import os
import pandas as pd
from dotenv import load_dotenv

In [43]:
load_dotenv()
s3=boto3.resource(
    service_name='s3',
    region_name=os.getenv('AWS_DEFAULT_REGION'),
    aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key =os.getenv('AWS_SECRET_ACCESS_KEY'))

                                                    Create bucket

In [ ]:
bucket =s3.create_bucket(Bucket="sanjay-test-bucket1",CreateBucketConfiguration ={'LocationConstraint':'ap-south-1'})

                                            Show the all Buckets in S3

In [33]:
for bucket in s3.buckets.all():
    print(bucket.name)

sanjay-test-bucket1

                                        Upload the file from the local

In [35]:
s3.Bucket('sanjay-test-bucket1').upload_file(r'C:\Users\sanju\bridgelab_local files\AWS_boto3\anual.csv','anual.csv')

In [39]:
for obj in s3.Bucket('sanjay-test-bucket1').objects.all():
    print(obj)

s3.ObjectSummary(bucket_name='sanjay-test-bucket1', key='anual.csv')

                                           Read the data from the s3 bucket file

In [27]:
obj_get=s3.Bucket('sanjay-test-bucket1').Object('anual.csv').get()
pd.read_csv(obj_get['Body'],index_col=0)

,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
Year,,,,,,,,,
2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,7426,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,30814,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,147663,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,269,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1639,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,566979,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,23176,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,80778,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H22,Closing stocks,Financial performance,88197,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,105450,ANZSIC06 divisions A-S (excluding classes K633...

                                         Download File from local

In [40]:
s3.Bucket('sanjay-test-bucket1').download_file(Key='anual.csv',Filename='download.csv')
pd.read_csv('download.csv',index_col=0)

,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
Year,,,,,,,,,
2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,55267,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,7426,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,30814,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,147663,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,269,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1639,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,566979,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,23176,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,80778,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H22,Closing stocks,Financial performance,88197,ANZSIC06 divisions A-S (excluding classes K633...
2023,Level 1,99999,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,105450,ANZSIC06 divisions A-S (excluding classes K633...

                               Delete the objects in the s3 bucket

In [49]:
bucket=s3.Bucket('sanjay-test-bucket1')
bucket.objects.all().delete()

[{'ResponseMetadata': {'RequestId': '6RPXA7Z2XFVR8RWH',
   'HostId': 'wQsLxAgRUemksmUSdamu3+pDr8SML9mIXkxBjgDINrGVbgMgssgzgf4Esw2OT+LehOsQhhHjoAg=',
   'HTTPStatusCode': 200,
   'HTTPHeaders': {'x-amz-id-2': 'wQsLxAgRUemksmUSdamu3+pDr8SML9mIXkxBjgDINrGVbgMgssgzgf4Esw2OT+LehOsQhhHjoAg=',
    'x-amz-request-id': '6RPXA7Z2XFVR8RWH',
    'date': 'Mon, 16 Sep 2024 11:47:54 GMT',
    'content-type': 'application/xml',
    'transfer-encoding': 'chunked',
    'server': 'AmazonS3',
    'connection': 'close'},
   'RetryAttempts': 0},
  'Deleted': [{'Key': 'anual.csv'}]}]

                                      delete the bucket

In [50]:
bucket=s3.Bucket('sanjay-test-bucket1')
bucket.delete()

{'ResponseMetadata': {'RequestId': 'Y276N554HD7J3E9D',
  'HostId': 'IvqoCeWrIeyJdM9Q76SLO48HrHNG9ZoKXGUzDPsUGy8S0fZktca56LBbgXgR2GyyJJZZSMToNCMvErCt0Umd0A==',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': 'IvqoCeWrIeyJdM9Q76SLO48HrHNG9ZoKXGUzDPsUGy8S0fZktca56LBbgXgR2GyyJJZZSMToNCMvErCt0Umd0A==',
   'x-amz-request-id': 'Y276N554HD7J3E9D',
   'date': 'Mon, 16 Sep 2024 11:50:42 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}